project_id = "drhqhjfbcatnifqrnyrd"

[functions.ai-feedback]
verify_jwt = false

[functions.upload-signer]
verify_jwt = false

[functions.operator-notify]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

